language: go

sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
  - glide install
