language: go

sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - curl https://glide.sh/get | sh
  - glide install
